<?php
// $Id: potx_test_7.module,v 1.1.2.2 2009/10/20 15:49:36 goba Exp $

/**
 * @file
 *   File used purely to test the parser in potx.
 */

/**
 * Implementation of hook_menu()
 */
function potx_test_7_menu() {
  $items = array();
  $items['translate/test'] = array(
    'title' => 'Test menu item',
    'description' => 'This is a test menu item',
    'page callback' => 'potx_test_7_page',
  );
  $items['translate/test-empty'] = array(
    'title' => '',
  );
  return $items;
}

function potx_test_7_page() {
  t('This is a test string.');
  format_plural($count, '1 test string', '@count test strings');
  watchdog('test watchdog type', 'My watchdog message');

  st('Installer only test string');
  $t('Dynamic callback test string');
  
  t('Test string in context', array(), array('context' => 'Test context'));
  t('');
}

function potx_test_7_perm() {
  return array('test potx permission', 'one more test potx permission', '');
}

function potx_test_7_permission() {
  return array(
    'test potx permission' => array(
     'title' => t('Test potx permission'),
     'description' => t('Test potx permission description'),
    ),
    'one more test potx permission' => array(
     'title' => t('One more test potx permission'),
     'description' => t('One more test potx permission description'),
    ),
  );
}
